sudo: required
services:
  - docker

before_install:
  - docker build -t sampletest -f ./client/Dockerfile.dev ./client

# -- --coverage is added to exit the process after running the tests
script:
  - docker run sampletest npm test -- --coverage

after_success:
  - docker build -t tanoybhowmick/multi-client ./client
  - docker build -t tanoybhowmick/multi-nginx ./nginx
  - docker build -t tanoybhowmick/multi-server ./server
  - docker build -t tanoybhowmick/multi-worker ./worker
  #login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push those images to docker hub
  - docker push tanoybhowmick/multi-client
  - docker push tanoybhowmick/multi-nginx
  - docker push tanoybhowmick/multi-server
  - docker push tanoybhowmick/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY